services:
  backend:
    container_name: flaskbackend
    image: flaskbackendv1
    ports: 5000:5000
    depends_on: mongo

  mongo:
    container_name: mongo
    image: mongo:4.2.0
    ports: 1048:27017

  